# Generated by Django 4.2.7 on 2024-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending')], default='pending', max_length=200),
        ),
    ]
