# Generated by Django 4.2.7 on 2024-03-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policeprofile',
            name='officer_details',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=200),
        ),
        migrations.CreateModel(
            name='policeofficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('dob', models.DateField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/profile')),
                ('rank', models.CharField(max_length=300)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_station', to='app.policeprofile')),
            ],
        ),
    ]
