# Generated by Django 4.2.7 on 2024-03-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending')], default='pending', max_length=200),
        ),
    ]
