# Generated by Django 4.2.7 on 2024-04-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_policeprofile_email_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='guardianname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to='app.userprofile'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='guardianphone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardianph', to='app.userprofile'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='userphone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userph', to='app.userprofile'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=200),
        ),
    ]
