# Generated by Django 4.2.7 on 2024-04-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_complaint_guardianname_complaint_guardianphone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='guardianname',
            new_name='guardian_name',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='guardianphone',
            new_name='guardian_phone',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending')], default='pending', max_length=200),
        ),
    ]
