# Generated by Django 4.2.4 on 2024-04-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='userphone',
        ),
    ]
