# Generated by Django 4.2.4 on 2024-04-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_complaint_guardian_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policeprofile',
            name='email',
        ),
    ]
